### ISSUE TITLE
Chrome 103 - The script is not trigger until you quit chrome

### ISSUE THREAD

**Issue by behrooz-tahanzadeh** [danielnitz/zebra-printing-chrome-extension#3]
I can only see the `content.js loaded` message in the console. I've been testing this on Mac but I believe it behaves the same on windows.
The message is triggered only when I quit chrome.

**Comment by danielnitz** [comment]
I cannot reproduce this issue. Considering the time that has passed, I'll close this. Feel free to open a new ticket if this is still an issue for you.
